### PR TITLE
TypeError: undefined is not an object (evaluating 't.renderTasks')

### PR DESCRIPTION
**Pull request by Sandravaphilips**

### CODE REVIEW

**Comment by Sandravaphilips** [comment]
I was unable to reproduce this error. But I did find out that it's from pdfjs. For now, I've updated the package to a safer version. I'd like to see if that solves it. If not, I'll investigate further.

**Comment by longhotsummer** [comment]
Ref https://github.com/laws-africa/peachjam/issues/1458

**Comment by longhotsummer** [comment]
2.16.105 is the last in the 2.x release line, and seems like a good bet.

The package-lock.json will need to be updated for this to work correctly.

The other thing I need to check is that `bin/pdfjs-to-text` produces the same text on both versions. We rely on that to ensure that text overlays work correctly with the annotations extracted based on `DocumentContent.content_text`, which comes from `bin/pdfjs-to-text`. I have looked through the changelog and don't see anything that concerns me (the last major change to text extraction was before 2.14).

**Comment by longhotsummer** [comment]
A random sample of 8 PDFs from TanzLII shows that 3 of them have minor whitespace differences (actually for the better -- newlines are added where they should have been before). Example (first version is 2.14, second is 2.16):

```
*** 2.14/KGIntertrade Company (T) Ltd vs TIB Development Bank Ltd  3 Other (Land Case 292 of 2022) 2023 TZHCLandD 16787 (16 August 2023).pdf.txt	2023-08-31 11:21:09.000000000 +0200
--- 2.16/KGIntertrade Company (T) Ltd vs TIB Development Bank Ltd  3 Other (Land Case 292 of 2022) 2023 TZHCLandD 16787 (16 August 2023).pdf.txt	2023-08-31 11:20:05.000000000 +0200
***************
*** 4,10 ****
  LAND CASE NO. 292 OF 2022
  KG - INTERTRADE COMPANY (T) LTD...............................PLAINTIFF
  VERSUS
! TIB DEVELOPMENT BANK LTD....................................1st DEFENDANTTHE HON. ATTORNEY GENERAL.................................2nd DEFENDANT
  MELVA INTERNATIONAL LTD ........................... 3rd DEFENDANT
  TRUST COMPANY LTD............................................... 4th DEFENDANT
  RULING
--- 4,11 ----
  LAND CASE NO. 292 OF 2022
  KG - INTERTRADE COMPANY (T) LTD...............................PLAINTIFF
  VERSUS
! TIB DEVELOPMENT BANK LTD....................................1st DEFENDANT
! THE HON. ATTORNEY GENERAL.................................2nd DEFENDANT
  MELVA INTERNATIONAL LTD ........................... 3rd DEFENDANT
  TRUST COMPANY LTD............................................... 4th DEFENDANT
  RULING
***************
*** 74,80 ****
  "14 subject to the pecuniary or other limitations prescribed by
  any law, suits:
  4
   (a) for the recovery of immovable property with or
! without rent or profits;(b) for the partition of the immovable property;
  (c) for foreclosure, sale or redemption in the case of a
  mortgage ofora charge upon immovable property;
  (d) for the determination of any other rights to, or
--- 75,82 ----
  "14 subject to the pecuniary or other limitations prescribed by
  any law, suits:
  4
   (a) for the recovery of immovable property with or
! without rent or profits;
! (b) for the partition of the immovable property;
  (c) for foreclosure, sale or redemption in the case of a
  mortgage ofora charge upon immovable property;
  (d) for the determination of any other rights to, or
```

**Comment by longhotsummer** [comment]
In most cases these minor changes won't make a huge difference, because our annotations will adjust based on the prefix/suffix. However, it isn't guaranteed and there may be ongoing creep.

So, ideally, we should re-extract all text and re-extract citations annotations for PDF documents.

**Comment by longhotsummer** [comment]
I'm able to reproduce this on my iphone. It seems to happen when the page is loaded in portrait, then rotated to landscape and reloaded (or vice versa). It doesn't always happen, but after a few tries the PDF doesn't render properly, and the error is sentry to sentry (although it isn't sent to the console).

**Comment by longhotsummer** [comment]
Found the issue. Upgrading the library won't help.

image

**Comment by longhotsummer** [comment]
I'm going to close this and take the discussion back to https://github.com/laws-africa/peachjam/issues/1458

**Pull request closed without merging**
