### PR TITLE
Ingest aliases

### PR DESCRIPTION
**Pull request by nickmwangemi**

### CODE REVIEW

**Review by longhotsummer — DISMISSED** [review]
Looks good. However, until Indigo has this field added, it will break because `document["aliases"]` won't exist.

So either you need to wait until it's deployed. Or, make it more robust with:

```
aliases = document.get("aliases", [])
```

that's probably easier and safer

**Review by longhotsummer — APPROVED** [review]

**Comment by shailen-naidoo** [comment]
This looks great, I am going to give it a try.

**Comment by shailen-naidoo** [comment]
I tried this on the site but it is not working, I am assuming that it is merged in but still needs to be QA tested?

**Comment by longhotsummer** [comment]
Hi @shailen-naidoo the supporting part of this in another system is not yet enabled.

**Pull request merged**
