### PR TITLE
Fix wrapping on document detail page

### PR DESCRIPTION
**Pull request by nickmwangemi**
Without relationships
image

With relationships
image

### CODE REVIEW

**Comment by longhotsummer** [comment]
@nickmwangemi this isn't achieving what the original issue asks for. The second column should effectively not be there if there are no relationships.

**Comment by nickmwangemi** [comment]
> @nickmwangemi this isn't achieving what the original issue asks for. The second column should effectively not be there if there are no relationships.

I'll sort it out

**Review by longhotsummer — APPROVED** [review]
nice :)

**Comment by longhotsummer** [comment]
Agh, damn, now the key-value pairs are too far apart! :(

**Comment by longhotsummer** [comment]
I'll open another issue, I think musango needs to brew up some fancier CSS.

**Pull request merged**
