### PR TITLE
Add a link to Help under search on Main Page

### LINKED ISSUE #1652: Add a link to Help under search on Main Page
image

### PR DESCRIPTION
**Pull request by Sandravaphilips**
Closes #1652
Screenshot 2024-01-17 at 13 24 06

### CODE REVIEW

**Comment by longhotsummer** [comment]
it needs to link to the help for search.

**Comment by Sandravaphilips** [comment]
@longhotsummer updated. Is it okay this way or should we still rely on peachjam settings?

**Comment by longhotsummer** [comment]
@Sandravaphilips use `{{ PEACHJAM_SETTINGS.user_help_link }}` as the base, then the rest can be hard-coded. See how other views have populated the `link` URL.

**Comment by Sandravaphilips** [comment]
@longhotsummer is this what you mean?
Screenshot 2024-01-17 at 13 58 13

**Pull request merged**
