### PR TITLE
Reduce unused Javascript to decrease bytes consumed by network activity as a measure to improve performance scores.

### PR DESCRIPTION
**Pull request by Sandravaphilips**
Issue https://github.com/laws-africa/peachjam/issues/1318

There were only a few modules not being used, so I'm unsure if it'll significantly reduce bytes. I tried looking for a way to use a CDN for this project, but it was taking too long to find a working method. 

For now, the files are still present in Bootstrap; they just aren't imported.

### CODE REVIEW

**Comment by longhotsummer** [comment]
@Sandravaphilips how easy is it to explicitly import the bootstrap JS into our typescript/javascript code, since we use webpack? Then it  would be included in app.js and not imported using a separate `<script>` tag.

See the docs here: https://getbootstrap.com/docs/5.0/customize/optimize/#lean-javascript

**Comment by Sandravaphilips** [comment]
@longhotsummer is this what you meant? If it is, then it'll also solve the Tab issue of  #1334

**Review by longhotsummer — APPROVED** [review]
yup, spot-on

**Comment by longhotsummer** [comment]
Pls don't merge this quite yet.

**Comment by longhotsummer** [comment]
@Sandravaphilips rather than importing the js from the bundled js, can you see if it's possible to do that from an npm-installed version of bootstrap via package.json? Then we don't need to host the bootstrap JS in our repo at all.

**Comment by longhotsummer** [comment]
I've done this for the SCSS, it should be straight-forward to do it for the javascript now too. Thanks.

**Comment by Sandravaphilips** [comment]
@longhotsummer It's done now.

**Comment by longhotsummer** [comment]
I had to add @types/bootstrap for it to compile, but this looks good to me.

**Comment by Sandravaphilips** [comment]
Oh, I forgot I installed that. I usually avoid pushing changes to lock.json, so I only push the files I worked on. I'll merge now

**Review by longhotsummer — APPROVED** [review]

**Pull request merged**
