### PR TITLE
Handle blank soffice output

### PR DESCRIPTION
**Pull request by longhotsummer**

### CODE REVIEW

**Comment by actlikewill** [comment]
It now uploads without the error. However, the document now exists without content html. There will be no way for me to know which other documents have errors and isolate them during import.

**Comment by longhotsummer** [comment]
Can you check for empty `content_html`?

**Comment by actlikewill** [comment]
> 

We can check for empty html at the step where we extract. I can push on to this branch if that is ok.

**Comment by longhotsummer** [comment]
> > 
> 
> We can check for empty html at the step where we extract. I can push on to this branch if that is ok.

Yup, go for it -- add whatever you need.

**Pull request closed without merging**
