### PR TITLE
Admin

### PR DESCRIPTION
**Pull request by longhotsummer**
* move admin into peachjam
* update admin forms to group related fields, put important ones first, and hide advanced ones

image

### CODE REVIEW

**Review by actlikewill — COMMENTED** [review]
When saving a document from the admin, if fails if there is no work. 'CoreDocument has no work is the error'

**Comment by actlikewill** [comment]
```
 if self.work_frbr_uri and (
            not self.work or self.work.frbr_uri != self.work_frbr_uri
        )
```
This logic in the coredocument save method seems to always result in false so no work gets created.

**Comment by longhotsummer** [comment]
@actlikewill thanks, fixed.

**Review by actlikewill — APPROVED** [review]
Looks good.

**Pull request merged**
