### PR TITLE
Lawreader

### PR DESCRIPTION
**Pull request by longhotsummer**
* updated styles for books for lawreader
* TOC shows active portion only at first level (otherwise behaves like normal below that)
* don't randomize generated TOC ids, to allow them to work when shared
* allow blockquote in html
* adjust CSS styles for book document type, for readability and visual interest

https://www.loom.com/share/7388e9997ec34af1b99748a8cd6c8b22

### CODE REVIEW

**Comment by actlikewill** [comment]
@longhotsummer I noticed that the Book model does not take on the "book" frbr_uri_subtype and so does not get the proper TOC treatment
I think that this pre_save method is not working properly: https://github.com/laws-africa/peachjam/blob/86cb721f6f87ea19afa16455c8e63e3128d642d2/peachjam/models/journals_books.py#L9C2-L14C1

**Comment by longhotsummer** [comment]
> @longhotsummer I noticed that the Book model does not take on the "book" frbr_uri_subtype and so does not get the proper TOC treatment I think that this pre_save method is not working properly: https://github.com/laws-africa/peachjam/blob/86cb721f6f87ea19afa16455c8e63e3128d642d2/peachjam/models/journals_books.py#L9C2-L14C1

Thanks. It looks like we need to force the `nature` object, i'll do that.

**Comment by longhotsummer** [comment]
> > @longhotsummer I noticed that the Book model does not take on the "book" frbr_uri_subtype and so does not get the proper TOC treatment I think that this pre_save method is not working properly: https://github.com/laws-africa/peachjam/blob/86cb721f6f87ea19afa16455c8e63e3128d642d2/peachjam/models/journals_books.py#L9C2-L14C1
> 
> Thanks. It looks like we need to force the `nature` object, i'll do that.

Fixed.

**Review by actlikewill — APPROVED** [review]
Works well :+1:

**Pull request merged**
