### PR TITLE
Colons, dates

### PR DESCRIPTION
**Pull request by longhotsummer**
* slugify to strip colons when uploading a new source file
* fix defaulting `frbr_uri_date` from `date` field

### CODE REVIEW

**Review by actlikewill — COMMENTED** [review]
@longhotsummer I keep getting a 'maximum recursion depth exceeded' error when uploading a source file.

**Comment by longhotsummer** [comment]
> @longhotsummer I keep getting a 'maximum recursion depth exceeded' error when uploading a source file.

Can you provide a stack trace?

**Comment by longhotsummer** [comment]
@actlikewill fixed

**Review by actlikewill — APPROVED** [review]
Works well.

**Pull request merged**
