### PR TITLE
Setup GhaLII, MalawiLII & ZambiaLII on peachjam

### PR DESCRIPTION
**Pull request by nickmwangemi**
ghalii

malawilii

zambialii

### CODE REVIEW

**Review by longhotsummer — COMMENTED** [review]
Looking good.

I was expecting to see some logos and possibly new banner images, based on the existing sites.

**Comment by longhotsummer** [comment]
> Looking good.
> 
> I was expecting to see some logos and possibly new banner images, based on the existing sites.

Also, some custom SCSS for each site to customise the primary brand colour?

**Comment by actlikewill** [comment]
@longhotsummer We've added the logos and the banner images. We've also moved some context data for the home page to the liiweb base class. If  the primary theme colors are available we can also add them. Otherwise I think we are about ready.

**Comment by nickmwangemi** [comment]
> @longhotsummer We've added the logos and the banner images. We've also moved some context data for the home page to the liiweb base class. If the primary theme colors are available we can also add them. Otherwise I think we are about ready.

We can pick the primary theme colors from the existing sites.

**Review by longhotsummer — DISMISSED** [review]

**Pull request merged**
