### PR TITLE
simplified judgment relationships with ajax dropdowns

### PR DESCRIPTION
**Pull request by longhotsummer**
Closes https://github.com/laws-africa/peachjam/issues/1245

* new "related judgments" tab (for judgments only right now)
* this links to the relationship system; the user must choose an appropriate predicate and subject work
* autocomplete/search dropdown for choosing works
* outstanding: use autocomplete/search dropdowns for choosing works in the relationships section of the work admin view

image

### CODE REVIEW

**Comment by longhotsummer** [comment]
@nickmwangemi pls can you add the autocomplete for the predicates in the work admin view.

**Comment by nickmwangemi** [comment]
image

**Comment by actlikewill** [comment]
@nickmwangemi are we able to filter the queryset to the overturns only?

**Comment by longhotsummer** [comment]
> @nickmwangemi are we able to filter the predicates to the overturns only? and maybe the works to judgments only?

I was also thinking that, and thinking of filtering options to judgments only. For the first iteration, I thought that would be too smart. Most judgments don't have relationships at all, so there won't be a very confusing list.

**Review by actlikewill — APPROVED** [review]
Neat, both libraries are a great addition. :+1:

**Comment by actlikewill** [comment]
> @nickmwangemi Just saw that there was a request for autocomplete for predicates

ah I see its for the work admin view :+1:

**Pull request merged**
