### PR TITLE
Fix year filter facet

### PR DESCRIPTION
**Pull request by nickmwangemi**
https://www.loom.com/share/78a869015e964d59aa9c038305386e9a

### CODE REVIEW

**Comment by nickmwangemi** [comment]
Closes https://github.com/laws-africa/peachjam/issues/508

**Comment by longhotsummer** [comment]
Please add a loom to demo that this is tested and working as expected.

**Comment by nickmwangemi** [comment]
https://www.loom.com/share/78a869015e964d59aa9c038305386e9a

**Review by longhotsummer — APPROVED** [review]
Great

**Pull request merged**
