### PR TITLE
GIZ logos

### PR DESCRIPTION
**Pull request by actlikewill**
image

image

image

image

### CODE REVIEW

**Comment by actlikewill** [comment]
@longhotsummer hopefully the GhaLII logos don't look too cluttered :thinking:

**Review by nickmwangemi — APPROVED** [review]

**Comment by longhotsummer** [comment]
Please don't merge quite yet, we're still confirming this is the correct logo. There are multiple GIZ logos.

**Comment by actlikewill** [comment]
> Please don't merge quite yet, we're still confirming this is the correct logo. There are multiple GIZ logos.

Ok. I looked through the attachments and these seemed appropriate. I cropped some of the white space to get them to fit better.

**Comment by longhotsummer** [comment]
Updated logos based on branding requirements:

image

In particular:

* "Only the GIZ logo with the addition ‘Implemented by’ may be used in combination with the German cooperation logo." - https://www.giz.de/cdc/en/html/59568.html
* "The logos of implementing organizations (e.g. GIZ, KfW) are to be placed beside or beneath the cooperation logo with the
words “implemented by” in the relevant official language. The ratio of 100% of the English cooperation logo to 80%
of the implementing organization logo must be adhered to here." - https://www.giz.de/cdc/en/downloads/manual-ELdZ-en-16may2013.pdf

**Pull request merged**
