### PR TITLE
Search tweaks

### LINKED ISSUE #1462: As a user of a LII website, I would like to filter my search results by Reported cases only
Offer the user a filter option for only Reported cases. Suggested this be placed above the search results and not in the left sidebar, so users can switch on and off the reported cases results
image

### PR DESCRIPTION
**Pull request by actlikewill**
- [x] Facet Option Badges
- [x] Scroll to top of search page on search
- [x] Toggle advanced search back to search after click
- [x] Move sort by above doc count in mobile view
- [x] Found more than 10,000 documents
- [x] Change h5 result title

https://www.loom.com/share/41b23a15915446beafd6a8c42920b94f?sid=bb185d5d-bae9-4268-94a4-cbe6ce2066c3

closes #1462

### CODE REVIEW

**Comment by actlikewill** [comment]
one more thing: https://www.loom.com/share/b1b72909f3504d8bb4506a9fad091ad6

**Comment by actlikewill** [comment]
@longhotsummer I found the above bug while working on this issue,

**Comment by longhotsummer** [comment]
> @longhotsummer I found the above bug while working on this issue,

Fun!

I think the root cause is that we allow a facet to be active even when no search results match that facet. Maybe we need to compare the chosen facet values against the aggregates that we get back from ES, and only allow active facet values that are also in the list of values returned by ES. This should be relatively easy to do  inside the facet component.

**Review by longhotsummer — APPROVED** [review]
Great

**Pull request merged**
