### PR TITLE
Gazettes admin

### PR DESCRIPTION
**Pull request by actlikewill**
https://www.loom.com/share/a25fd4e5be0247cd8d1b9ac7eaae07f5?sid=820a5d07-520d-4730-bac0-a75fae749b4d

closes https://github.com/laws-africa/kenyalaw-pj/issues/194
closes https://github.com/laws-africa/kenyalaw-pj/issues/195

### CODE REVIEW

**Comment by actlikewill** [comment]
@niiroobiro you can take a look at the loom and the changes to the gazette admin, feedback welcome

**Comment by longhotsummer** [comment]
@actlikewill I think it's important that the "Additional details" and "Tasks" tabs are still there. Is it possible to implement what you have but by overriding/extending the fieldsets from `CoreDocumentAdmin`? That will ensure you "inherit" that functionality.

Please double check our treatment of the "publication" and "sub-publication" fields, we could possibly put those under advanced.

**Comment by longhotsummer** [comment]
Also the "Work Identification" is important for debugging.

**Comment by actlikewill** [comment]
@longhotsummer i've added back the tabs you suggested:
image
also moved the sub-publication and publication fields to the advanced tab

**Review by longhotsummer — APPROVED** [review]
great, i'm more comfortable with this because it means any future changes to documentadmin will be included here.

**Comment by niiroobiro** [comment]
@actlikewill Simple and straight forward. Nice.

**Pull request merged**
