### PR TITLE
use p99 as pagerank pivot

### PR DESCRIPTION
**Pull request by longhotsummer**
the geometric mean is too small; only at higher values do we get reasonable score influence

see https://colab.research.google.com/drive/1KlYC7A9JeqS_uaLhL8yv_IrAmHHXNCdK

### CODE REVIEW

**Comment by actlikewill** [comment]
@longhotsummer I dont have permissions to view the collab, Is it yours?

**Comment by longhotsummer** [comment]
with pivot (k) = p99:

image

with geometric mean:

image

**Comment by longhotsummer** [comment]
> @longhotsummer I dont have permissions to view the collab, Is it yours?

@wilson moved into shared folder, try now?

**Review by actlikewill — APPROVED** [review]
interesting. maybe at some point we should discuss these changes in a bit more detail so I can understand it better.

**Comment by longhotsummer** [comment]
> interesting. maybe at some point we should discuss these changes in a bit more detail so I can understand it better.

definitely. i can't say that I'm a pro, but I can outline how it works.

**Pull request merged**
