### PR TITLE
Add ckeditor to admin

### LINKED ISSUE #216: As an editor I'd like CKEditor to make editing HTML fields easier
* ckeditor 5
* fields: content_html
* don't use ckeditor (or make the field readonly) if the content_html_is_akn field is set.

Disallow these ckeditor features:

* images (until we can sort this out in detail)

### PR DESCRIPTION
**Pull request by actlikewill**
closes #216 

ckeditor

### CODE REVIEW

**Comment by longhotsummer** [comment]
@actlikewill if we need python 3.8 (if that's the problem here), I don't see a huge reason not to upgrade to that. 3.7 is EOL in 11 months.

**Comment by actlikewill** [comment]
@longhotsummer Do we need to alter dynamically alter the widget using javascript? i.e when the user checks the content_html_akn box we hide the field or make it readonly?

**Review by longhotsummer — DISMISSED** [review]
Looks good. Disabling the field as you've done it is sufficient for now.

**Comment by longhotsummer** [comment]
We probably need to make `headnote_holding` on judgment also an  HTML field with CKeditor, I'll confirm shortly.

**Comment by longhotsummer** [comment]
Let's go ahead and merge this and we can add more fields later if/when required.

**Pull request merged**
