### PR TITLE
Place detail view

### PR DESCRIPTION
**Pull request by longhotsummer**
* place detail view
* list of RECs on the africanlii homepage
* bootstrap-style paginator
* the paginator currently discards page filters, see #379 

image

image

image

Requires https://github.com/laws-africa/peachjam/pull/377

### CODE REVIEW

**Review by actlikewill — COMMENTED** [review]
@longhotsummer You mention issue #379 but I can't seem to see a fix.

**Comment by longhotsummer** [comment]
> @longhotsummer You mention issue #379 but I can't seem to see a fix.

The bug isn't fixed yet. #379 is to record that we need to fix it, which will happen once this is merged.

**Comment by longhotsummer** [comment]
> > @longhotsummer You mention issue #379 but I can't seem to see a fix.
> 
> The bug isn't fixed yet. #379 is to record that we need to fix it, which will happen once this is merged.

This is an existing bug, so after this PR we're no worse than before it.

**Review by actlikewill — APPROVED** [review]
Looks good.

**Pull request merged**
