### PR TITLE
Disclaimer in metadata

### LINKED ISSUE #1502: As a legislation user I want to see the disclaimer on a stub, too
Here is a stub on edit.laws.africa: https://edit.laws.africa/works/akn/mw/act/gn/1963/283/
It includes a disclaimer, "The publication date of this work could not be ascertained. We used the date 31 December 1963 because the work was published during the course of the year 1963."

Here is the same Act on MalawiLii: https://malawilii.org/akn/mw/act/gn/1963/283/eng@1963-12-31
The content hasn't been marked up, so we're displaying the source PDF, which means there's no generated coverpage, and therefore the disclaimer isn't showing anywhere.

### PR DESCRIPTION
**Pull request by actlikewill**
image

closes #1502

### CODE REVIEW

**Comment by actlikewill** [comment]
@goose-life how much text is in a disclaimer typically, if its not too long this should be okay

**Comment by goose-life** [comment]
> @goose-life how much text is in a disclaimer typically,? if its not too long this should be okay

Here's a typical one used in Malawi: 
"The publication date of this work could not be ascertained. We used the date 31 December 1963 because the work was published during the course of the year 1963."

**Comment by actlikewill** [comment]
@goose-life For that text,  we could add the disclaimer as part of the notices:
image

**Review by longhotsummer — APPROVED** [review]
lgtm

**Pull request merged**
