### PR TITLE
Images and social media in article

### LINKED ISSUE #1496: As a website user, I would like to be able to see the accompanying photo of an article without having to use a magnifying glass
In the Recent articles by the same author column

image

### LINKED ISSUE #1497: Add social media sharing buttons on Articles
There is no social media buttons ribbon here .. 

https://africanlii.org/articles/2023-08-29/carmel-rickard/court-orders-reporting-shroud-over-upcoming-divorce-hearing

### PR DESCRIPTION
**Pull request by actlikewill**
- [x] Adjust images list
- [x] Social media 

closes #1497
closes #1496

image

image

### CODE REVIEW

**Comment by actlikewill** [comment]
@nickmwangemi Forgive the screenshots, they are of other screenshots

**Comment by longhotsummer** [comment]
@actlikewill what does it look like on mobile?

**Comment by actlikewill** [comment]
@longhotsummer I've added screenshots for mobile view. I added a new template for showing recent articles only,

**Comment by actlikewill** [comment]
@longhotsummer I've updated the pr as discussed: https://www.loom.com/share/ddb89f0b33084a7e8ca15462da7f4504?sid=33222628-5355-4e15-9409-de8941361dad

**Review by longhotsummer — APPROVED** [review]

**Pull request merged**
