### PR TITLE
Fix author facet

### LINKED ISSUE #353: When searching, I want better context on a search result
* full locality information
* author information, when available

### PR DESCRIPTION
**Pull request by actlikewill**
- Fixes the author facet in the search results.
- The authors index was not renamed when we renamed the model from authoring body to author. 
- Index will need to be rebuilt

closes #353

### CODE REVIEW

**Comment by actlikewill** [comment]
@musangowope Kindly confirm if the changes to the component are okay.

**Review by musangowope — APPROVED** [review]

**Comment by actlikewill** [comment]
@longhotsummer Should I commit app-prod.js?

**Review by longhotsummer — APPROVED** [review]
GitHub will build and commit the updated js, so it doesn't really matter. Once this is merged the index must be updated, search will break until it is

**Comment by actlikewill** [comment]
@longhotsummer There is also this stencil file that I have committed. Should I leave it in or remove it?

**Review by musangowope — APPROVED** [review]

**Pull request merged**
